#Default port is 8761
server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/
  instance:
    hostname: eureka-server2
    appname: eureka-server
    #preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # 关闭保护机制
    enable-self-preservation: false
    #剔除失效服务间隔
    eviction-interval-timer-in-ms: 4000


#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

